### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by edunham** [zenirc/zenircbot-lastfm#2]
This repo is public, but it's not easy to find out how I'm allowed to use or share the code. Could you add a LICENSE file to make it easier for users to understand how you'd like it to be used?

http://choosealicense.com/ might be helpful here.

Thanks!

**Comment by wraithan** [comment]
Whoops forgot to license this when I moved it into its own repo. I'll add
ISC when I get a chance. Thanks!
